### ISSUE TITLE
Click and wheel events on minimap broken?

### ISSUE THREAD

**Issue by FlexiGit** [bpmn-io/diagram-js-minimap#12]
With current version of diagram-js (0.27.2) the minimap and diagram show unexpected behavior.

When I click in the "white" area in the minimap (outside the dragging area) the "parent" diagram turns blank and the dragging area in the minimap disappears.
On one occasion I could get everything back by moving the diagram, so I guess the viewport is somewhere off.

When I use the mousewheel anywhere on the minimap the same happens.

I tried to disable the events on the svg in the dev console and then it's working ok.
My current workaround is to stop propagating the events in event capturing phase on the parent container (djs-minimap-map).

IMHO those events should be removed from the minimap anyway. The UX would be much more intuitiv. Especially now that the zooming in the diagram is done with CTRL+wheel.

**Comment by mschulte** [comment]
Any new insights into this? We got a similar problem with minimap in version v0.5.5. Clicking the white area in minimap does not fokus the clicked area (centered). 

Regards,
Matthias

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js-minimap/commit/000e2716135a0f2b9f82c1fe4dd6d693755ec48a.
