### ISSUE TITLE
Improve Minimap

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js-minimap#24]
* [x] viewport outline only

    ![image](https://user-images.githubusercontent.com/7633572/41588731-d8f170be-73b2-11e8-97f9-476dffd0aa03.png)

* [x] highlight viewport using an overlay

    ![image](https://user-images.githubusercontent.com/7633572/41588868-3bcb1b7c-73b3-11e8-9900-e1ce47769810.png)

    Working example using CSS clip-path: https://jsfiddle.net/8n0guqft/1/

* [x] align scrolling with canvas scrolling (CTRL + scroll)

**Comment by nikku** [comment]
Released in `diagram-js-minimap@1.2.0`.
