### ISSUE TITLE
Not working on Internet Explorer

### ISSUE THREAD

**Issue by bigianb** [bpmn-io/diagram-js-minimap#25]
Tested on IE 11 but I think later versions will have an issue too.
The problem is the recent change to use css. This line:
https://github.com/bpmn-io/diagram-js-minimap/blob/master/lib/Minimap.js#L374

```
var viewport = this._viewport = svgCreate('rect');
domClasses(viewport).add('viewport');
```
is the root cause because classList is not supported for svg elements in Internet Explorer. See the footnote on:
https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

The solution is to set the attribute directly.

**Comment by nikku** [comment]
Rather than setting the classes via attributes we should use the appropriate [`tiny-svg`](https://github.com/bpmn-io/tiny-svg) helper. It handles SVG classes correctly, event in IE 11:

```
import {
  classes as svgClasses
} from 'tiny-svg';

svgClasses(...).add('asda');
```

@bigianb Would you be interested in filing a PR that fixes this?
