### ISSUE TITLE
Provide a pre-build version in CDN

### ISSUE THREAD

**Issue by pjotrsavitski** [bpmn-io/diagram-js-minimap#30]
Current implementation does not provide a pre-build distribution of the library that could be used in contexts that do not allow any build steps.

Would it be possible to provide those versions within a `dist` catalog (the way that bpmn-js itself does)?

**Comment by pinussilvestrus** [comment]
Can you explain the benefits of having such a pre-built version in your opinion? It would help us to evaluate the value.

+ We are always open for contribution 🙂

**Comment by pjotrsavitski** [comment]
I would guess that the value as such is not that beneficial to the majority of the users. The issue is that I have a context with no compiled JS and thus not really able to use the module imports.

There is a possibility to write the code that would then be built, packages and imported, yet I did want to avoid that to keep things simple and load stuff from CDN (really old style approach to doing stuff).

**Comment by pinussilvestrus** [comment]
Thanks for clarifying! We will probably have a look at this. I guess this will be not on our current roadmap, since the benefits are not that big.

**Comment by nikku** [comment]
You can consider to pre-bundle the library yourself. Something along those lines should do the job:

```
mkdir some-folder
cd some-folder
npm install webpack webpack-cli diagram-js-minimap
npx webpack ../diagram-js-minimap/index.js --output-library-target=umd2 --output-library=DiagramJsMinimap
```

This builds a UMD bundle for the library, exposed under the name `DiagramJsMinimap` to `some-folder/dist/main.js`.

**Comment by nikku** [comment]
Closing this issue. As @pinussilvestrus indicated we'll not implement a pre-packaged version anytime soon.
