### ISSUE TITLE
Minimap crashes when opening

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/diagram-js-minimap#36]
__Describe the Bug__

With the current release, the Minimap crashes when opening and interacting

![Aug-07-2019 08-29-30](https://user-images.githubusercontent.com/9433996/62599811-80d95f00-b8ed-11e9-8112-73deb7ca5335.gif)

Additionally, you can see following error popping up

```js
Minimap.js:725 Uncaught TypeError: Cannot read property 'width' of undefined
    at fitAspectRatio (Minimap.js:725)
    at mapMousePositionToDiagramPoint (Minimap.js:697)
    at setViewboxCenteredAroundClickEvent (Minimap.js:73)
    at SVGSVGElement.onMousedown (Minimap.js:101)
```

__Steps to Reproduce__

1. Open Minimap
2. Move a little around the minimap box

__Expected Behavior__

Should not crash and simply work.

__Environment__

Please complete the following information:

 - Browser: Chrome 76
 - OS: macOS 10.14.5
 - Library version: 2.0.0

**Comment by pinussilvestrus** [comment]
It reveals the bug starts appearing with this commit: https://github.com/bpmn-io/diagram-js-minimap/commit/bfe7877c0091d7616359f5fde3ea0c2c488a228e

In https://github.com/bpmn-io/diagram-js-minimap/commit/58648d0e378b392e2cd9d3440a099fc0b31d77ff it is still working.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js-minimap/pull/37.
