### ISSUE TITLE
Minimap should always show full view of diagram content

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/diagram-js-minimap#4]
__Proposal for improvement__:
- Minimap should fit all shapes into the minimap window (with some minimal viewport)
- Zooming and moving on the canvas should affect only the semi-transparent view in the minimap

See [example](http://codepen.io/billdwhite/pen/QwpYZa) for the minimap behaviour.

**Comment by nikku** [comment]
The way to go!

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/diagram-js-minimap/commit/000e2716135a0f2b9f82c1fe4dd6d693755ec48a.
