### ISSUE TITLE
diagram-js-minimap@2.0.2 release issue

### ISSUE THREAD

**Issue by AndyBan** [bpmn-io/diagram-js-minimap#40]
The release includes a ".git\hooks\README.sample" file.

This makes npm think its a git repo when its not which makes it rather unhappy:
npm install
npm ERR! path c:\Path\node_modules\diagram-js-minimap
npm ERR! code EISGIT
npm ERR! git c:\Path\node_modules\diagram-js-minimap: Appears to be a git repo or submodule.
npm ERR! git     c:\Path\node_modules\diagram-js-minimap
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

**Comment by philippfromme** [comment]
I'm sorry about that. This is an [issue with npm](https://npm.community/t/npm-6-9-1-is-broken-due-to-git-folder-in-published-tarball/8454/13). We've released [another patch release](https://www.npmjs.com/package/diagram-js-minimap) (v2.0.3). Thanks for letting us know about the issue.
