### ISSUE TITLE
Minimap navigation breaks after resizing window

### ISSUE THREAD

**Issue by rehmulus** [bpmn-io/diagram-js-minimap#45]
__Describe the Bug__

Clicking the minimap navigates to a different position after resizing the viewport. The larger the difference between the sizes before and after resizing is, the larger is the discrepency between where I want to navigate and to where the minimap actually navigates.
Dragging the box will still work, but cannot be used if the viewport is outside the diagram so clicking the minimap should work properly.

This is how it looks
![](https://forum.bpmn.io/uploads/default/original/2X/4/460c71b9b32906203de0be425d3105f7d37df495.gif)

__Steps to Reproduce__

1. setup the environment, use one of these options
    - setup a project with diagram-js-minimap
    - go to https://codesandbox.io/s/minimap-demo-forked-n9gfr
    - checkout https://github.com/bpmn-io/bpmn-js-examples and `npm start` in minimap subdir
2. zoom in to some element so you can see the effect more easily
3. click the minimap once (everything should work as intended), if you skip step this then the resizing won't break the navigation
4. resize the window eg. by snapping the browser window to one side or by resizing the dev-tools
5. click the minimap again: now it navigates to a different position

__Expected Behavior__

The minimap should navigate to the position that was chosen on the minimap.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 92.0.4515.131
- OS: Windows 10
- Library version: 2.0.4

**Comment by nikku** [comment]
Thanks for your bug report. I can reproduce the issue.

**Comment by rehmulus** [comment]
Thank you! Didn't know about that.
Maybe you should include that snippet in the [examples ](https://github.com/bpmn-io/bpmn-js-examples/blob/master/minimap/app/app.js) then and in this projects [readme](https://github.com/bpmn-io/diagram-js-minimap/blob/master/README.md).

**Comment by nikku** [comment]
@rehmulus Glad it helped. 

Happy to take a PR to improve the existing example and documentation!
