### ISSUE TITLE
Minimap is incompatible with diagram-js@7

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/diagram-js-minimap#47]
__Describe the Bug__

I can not use the latest release with diagram-js@7

```
unhandled error in event listener TypeError: this._canvas.findRoot is not a function
    at Minimap._addElement (index.esm.js:588:1)
    at index.esm.js:273:1
    at bpmn-modeler.production.min.js:7:26123
```

__Steps to Reproduce__

1. Include this lib with bpmn-js@8
2. load a process
3. it blows up

__Expected Behavior__

It works

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: 2.1.0

**Comment by nikku** [comment]
In the spirit of `bpmn-js@8` is what we got right now we shall either un-publish what is broken (and publish a new major) or make it compatible (+ add integration tests that verify the compatibility).
