### ISSUE TITLE
Make possibility to open/close minimap more visible

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/diagram-js-minimap#5]
![minimap-toggle](https://cloud.githubusercontent.com/assets/7633572/25853513/58ff3028-34cd-11e7-8f5f-1b35632670b1.png)

**Comment by phillipalexander** [comment]
I spent 10m trying to figure out to close the minimap, then searched google and this open issue came up. Thanks for screenshot or I'd still be struggling!

**Comment by philippfromme** [comment]
@phillipalexander I'm sad to hear that. This is why we need to improve the minimap!

**Comment by nikku** [comment]
We now show an open / close indicator that should make it more visible.

Fixed on master.
