### ISSUE TITLE
Listen to events in minimap

### ISSUE THREAD

**Issue by FTW-001** [bpmn-io/diagram-js-minimap#65]
### Is your feature request related to a problem? Please describe.

Hello, I have integrated diagram-js-minimap4.0 in Camunda Bpmn, how do I listen to events in minimap through BpmnModeler?

**Comment by FTW-001** [comment]
For example：
const minimap = modeler.get('minimap');
minimap.on('',()=>{})...

**Comment by nikku** [comment]
> how do I listen to events in minimap through BpmnModeler?

This seems to be a question that we usually answer [via our community forum](https://forum.bpmn.io/).

What would you like to accomplish?

**Comment by FTW-001** [comment]
What I want to do is listen to the minimap area when I click or drag, and call back to handle some things.

**Comment by nikku** [comment]
> listen to the minimap area when I click or drag, and call back to handle some things.

Which things? What context do you need?

**Comment by FTW-001** [comment]
Sorry, there may be something wrong with what I described. I will send you a picture and you can help me see the reason. I click on the red area, but the yellow position is moved to the top

Is there a way to re-initialize or calibrate the positioning?
![WechatIMG1](https://github.com/bpmn-io/diagram-js-minimap/assets/61999790/678c411c-79b4-4407-b665-0e0b6137e0c1)

**Comment by FTW-001** [comment]
Instead of locating exactly where I clicked, I moved to the top or bottom, which is an occasional phenomenon,
The reason is that this is a page that can be swiped up and down, and the minimap becomes invisible when I swipe quickly, and the problem occurs when it is visible again

**Comment by FTW-001** [comment]
![1](https://github.com/bpmn-io/diagram-js-minimap/assets/61999790/85f477bd-f0af-4bc1-9973-b36a5b33d1c2)
![2](https://github.com/bpmn-io/diagram-js-minimap/assets/61999790/1cf0d64a-e5d0-4968-b112-c496d782942c)

**Comment by FTW-001** [comment]
我知道什么原因了，因为minimap相对于屏幕的位置是固定的，当页面支持滚动时，minimap相对于屏幕的位置也发生了改变，所以再次点击minimap时，就会出现定位不准确的问题。

你知道这种情况下该如何处理吗？ 或者有没有可以重新初始化或者重置当前位置的方法？ 
非常感谢。

**Comment by FTW-001** [comment]
I know why, because the position of minimap relative to the screen is fixed, and when the page supports scrolling, the position of minimap relative to the screen also changes, so when I click minimap again, I will have an inaccurate positioning problem.

Do you know what to do in this situation? Or is there a way to reinitialize or reset the current location?
Thank you very much.

**Comment by FTW-001** [comment]
Sorry to have taken up your time, but I have already solved the problem.

**Comment by nikku** [comment]
Thanks for the notice. Glad you solved it.
